/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package objetos;

import javax.swing.JOptionPane;

/**
 *
 * @author juran
 */
public class ventanaUno extends javax.swing.JFrame {

    /**
     * Creates new form ventanaUno
     */
    public ventanaUno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();
        cartatexto1 = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        etiqueta4 = new javax.swing.JLabel();
        etiqueta5 = new javax.swing.JLabel();
        etiqueta6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqueta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta.setText("Opcion 1 Realizar Una Suma");

        cartatexto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cartatexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartatexto1ActionPerformed(evt);
            }
        });
        cartatexto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cartatexto1KeyTyped(evt);
            }
        });

        boton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton.setText("Ingresar Datos");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        etiqueta1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta1.setText("Opcion 2 Realizar Una Resta");

        etiqueta2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta2.setText("Opcion 3 Realizar Una Multiplicacion");

        etiqueta3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta3.setText("Opcion 4 Realizar Una Division");

        etiqueta4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta4.setText("Opcion 5 Realizar Un Promedio");

        etiqueta5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta5.setText("Opcion 6 Realizar Una Potencia");

        etiqueta6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiqueta6.setText("Opcion 7 Realizar Una Radical");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("CALCULADORA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta2)
                    .addComponent(etiqueta3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta6, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartatexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(etiqueta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartatexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
                
                  String opcion;
                  
                  opcion = cartatexto1.getText();
                  
                  switch (opcion) {  
                      case "1":
                       operacion.formSuma fs = new operacion.formSuma();
                          
                          fs.setVisible(true);
                          fs.setLocationRelativo(null);
                         dispose(); 
                  break;
                       case "2":
                       operacion.formResta fr = new operacion.formResta();
                          
                          fr.setVisible(true);
                          fr.setLocationRelativo(null);
                         dispose(); 
                  break;
                  case "3":
                       operacion.formMulti fm = new operacion.formMulti();
                          
                          fm.setVisible(true);
                          fm.setLocationRelativo(null);
                         dispose(); 
                  break;
                  case "4":
                       operacion.formDivision fd = new operacion.formDivision();
                          
                          fd.setVisible(true);
                          fd.setLocationRelativo(null);
                         dispose(); 
                  break;
                  case "5":
                       operacion.formPromedio fp = new operacion.formPromedio();
                          
                          fp.setVisible(true);
                          fp.setLocationRelativo(null);
                         dispose(); 
                  break;
                  case "6":
                       operacion.formPotencia fpo = new operacion.formPotencia();
                          
                          fpo.setVisible(true);
                          fpo.setLocationRelativo(null);
                         dispose(); 
                  break;
                  case "7":
                       operacion.formRadical frad = new operacion.formRadical();
                          
                          frad.setVisible(true);
                          frad.setLocationRelativo(null);
                         dispose(); 
                  break;
                  default:
                        JOptionPane.showMessageDialog(null, "ERROR");
                          
                          
                          
                          
                          
                  }








        // TODO add your handling code here:
    }//GEN-LAST:event_botonActionPerformed

    private void cartatexto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cartatexto1KeyTyped
                      
              char dato = evt.getKeyChar();
              
              if(dato<'0' || dato>'9') {
                  evt.consume();
              }
              
        // TODO add your handling code here:
    }//GEN-LAST:event_cartatexto1KeyTyped

    private void cartatexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartatexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartatexto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaUno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JTextField cartatexto1;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel etiqueta4;
    private javax.swing.JLabel etiqueta5;
    private javax.swing.JLabel etiqueta6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
